name = "Better MC REDUX [Fabric 1.19.2]"
author = "MARCUSK"
version = "v18 MARCUSK"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "217e86feb2da861c0d9d723e78fb629d7138e6ef377d64a851bcf8a7e5d4ffbd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
