name = "Better MC REDUX [Fabric 1.19.2]"
author = "MARCUSK"
version = "v18 MARCUSK"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eecab5c9471a0101d58b2e2efd3eec04c37571c70b21ba099d908deead82961"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
