name = "Better MC REDUX [Fabric 1.19.2]"
author = "MARCUSK"
version = "v18 MARCUSK"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a3c37cf53f56353c73e136ba54a2ab2cf855adda01188bda0358497c0fb8542"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
