name = "Better MC REDUX [Fabric 1.19.2]"
author = "MARCUSK"
version = "v18 MARCUSK"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c158f0dde66a1779942e2d40c3ad1c324bc0f7b5325fc2587b48996b9b5f0ff"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
